### ISSUE TITLE
2nd Edition HTML Release Checklist

### ISSUE THREAD

**Issue by caridy** [tc39/ecma402#40]
* [x] Review hi-fi doc https://tc39.github.io/ecma402/ to match current pdf doc www.ecma-international.org/ecma-402/2.0/ECMA-402.pdf
* [x] Update build steps, re-org files and clean up the repo (caridy)
* [x] Produce HTML version using old-toc ecmarkup
* [x] Produce PDF from HTML
* [x] Tag 2nd edition code for posterity

**Comment by caridy** [comment]
@rwaldron let me know if I'm missing something here. Let's shoot for next meeting to get this out of the way.

contributors, we need all the help we can get to make sure that the html version matches what we have in the pdf, we need more eye-balls... please help!

**Comment by caridy** [comment]
https://github.com/tc39/ecma402/releases/tag/2.0
