### ISSUE TITLE
Editorial/Meta: Update editors

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma402#473]
- [ ] Update editors in the specs
- [ ] @tc39/ecma402-editors (WIP, pinged @gesa on IRC)
- [ ] ecma402-admin email list (@sffc can confirm this one)

+@gibson042 

Bonus, not required:

- [ ] I still need feedback from @gibson042 but I wonder if we should try out to add more people to the editor group and share the work.
- [ ] Set up a weekly editor's call, like the ECMA-262 editors have been doing.

**Comment by gesa** [comment]
@leobalter I got the push notification when you pinged me on IRC, but I no longer see the message in my client. I wonder if my bouncer lost some history through all of freenode's recent server update cycle. What specific updates need to be done? (also in the future I think this would be a good candidate for the Admin/Business issues queue so it can be an obvious to-do for the Chair group to get to) (I'm not saying I'm a flake, but… sometimes I'm a flake)

**Comment by leobalter** [comment]
Thank you @gesa. Who doesn't miss messages on IRC, robots? Add the fact IRCCloud was down for hours yesterday.

I'll confirm what we want for the changes in the TC39 github group and I'll file a proper issue in the Admin Business repo.

Thanks again!
